
package demo

// ---- auto generated by builder.go, NOT modify this file ----

import (
  field "github.com/xpwu/go-db-mongo/mongodb/field"
)

type Wx0FieldUpdaterF struct {
  *baseWx0Field
  *field.StructUpdaterF
}

func (s *Wx0FieldUpdaterF) FullName() string {
  return s.name
}

type Wx0FieldFilterF struct {
  *baseWx0Field
  *field.StructFilterF
}

func (s *Wx0FieldFilterF) FullName() string {
  return s.name
}

type Wx0Field struct {
  *baseWx0Field
  Wx0FieldUpdaterF  *Wx0FieldUpdaterF
  Wx0FieldFilterF   *Wx0FieldFilterF
}

func NewWx0Field(fName string) *Wx0Field {
  base := &baseWx0Field{fName}
  // 没有name时，不能做updater与filter操作，比如最顶层的Struct
  if fName == "" {
    return &Wx0Field {baseWx0Field:base}
  }
  up := &Wx0FieldUpdaterF{base, field.NewStructUpdaterF(fName)}
  fl := &Wx0FieldFilterF{base, field.NewStructFilterF(fName)}

  return &Wx0Field {base, up, fl}
}

// 对应于 bson struct 中的 inline 修饰符
func NewWx0FieldInline(fName string) *Wx0Field {
  return &Wx0Field {baseWx0Field: &baseWx0Field{fName}}
}

func (s *Wx0Field) FullName() string {
  return s.name
}

type baseWx0Field struct {
  name      string
}

func (s *baseWx0Field) Age() *field.PointField {
  n := field.StructNext(s.name, "Age")
  return field.NewPointField(n)
}

func (s *baseWx0Field) Time() *field.Int0F {
  n := field.StructNext(s.name, "Time")
  return field.NewInt0F(n)
}

